feat/added-restore-command
weseek/mongodb-awesome-backup pull request #1
Opened 2017-12-26 12:15 UTC by ryu-sato

refs INFRA-151:  S3 からバックアップファイルの DL と MongoDB リストアする機能を実装する

2017-12-27 04:34 UTC, skomma requested changes

2017-12-27 04:34 UTC, skomma commented on README.md
> +  [ -e BACKUPEDDAY=<Day which file is backuped specified in format yyyymmdd (default: <TODAY>) \ ]
ここはデフォルトオプション(backup, prune, list)するときの説明だから、ここに追記すべきじゃないと思う。
restore 用の手順は別に書くべき。

2017-12-27 04:34 UTC, skomma commented on bin/functions.sh
> +AWSCLI_PULL_OPT="s3 cp"
PUT と PULL 一緒なんだったら COPY_OPT とかにしてしまえば？

2017-12-27 04:34 UTC, skomma commented on bin/functions.sh
> +s3_pull_file() {
こっちも、put/pull がっちゃんこして s3_copy_file でいいと思う。

2017-12-27 04:34 UTC, skomma commented on README.md
> +  [ -e BACKUPEDDAY=<Day which file is backuped specified in format yyyymmdd (default: <TODAY>) \ ]
あと、変数名がすっごくわかりづらい。

2017-12-27 04:34 UTC, skomma commented on bin/restore.sh
> +mongorestore -h ${MONGODB_HOST} --drop -v ${TARGET} ${MONGORESTORE_OPTS}
drop するかどうかもオプション指定できたらいいんじゃないかなぁ？

2017-12-27 04:41 UTC, ryu-sato commented on README.md
> +  [ -e BACKUPEDDAY=<Day which file is backuped specified in format yyyymmdd (default: <TODAY>) \ ]
restore の説明項目は分けます。
元々の説明文章が README.md 内のデフォルトオプションだと言うことって書いてたっけ？
書かなくていいなら構わないけど気になった。

変数名分かりづらいか。restore したいファイルは PREFIX も何もなくてファイル名をそのまま指定させるようにしてみることにします。

2017-12-27 04:45 UTC, ryu-sato commented on bin/functions.sh
> +AWSCLI_PULL_OPT="s3 cp"
backup も restore も依存してしまうのは避けた方がいいと思ったけど強いこだわりでもないし、今回はDRYに従おうかな。

2017-12-27 04:46 UTC, ryu-sato commented on bin/functions.sh
> +s3_pull_file() {
修正します。

2017-12-27 04:47 UTC, ryu-sato commented on bin/restore.sh
> +mongorestore -h ${MONGODB_HOST} --drop -v ${TARGET} ${MONGORESTORE_OPTS}
なるほど。mongorestore とデフォルトの動作が違うのは確かに違和感あるので、
* デフォルトは --drop なし
* オプションで --drop 指定可能
にします。

2017-12-27 04:51 UTC, skomma requested changes

2017-12-27 04:51 UTC, skomma commented on README.md
> +  [ -e BACKUPEDDAY=<Day which file is backuped specified in format yyyymmdd (default: <TODAY>) \ ]
デフォルトオプションは今後書くべきだと思うけど、現時点では最低限の内容しか README.md には書いてない。

2017-12-27 04:51 UTC, skomma commented on bin/functions.sh
> +AWSCLI_PULL_OPT="s3 cp"
今後 awscli 以外を使うことはあまり考えられないからいいんじゃないかなぁ。
Amazon 公式だし。

2018-01-05 03:40 UTC, skomma requested changes

2018-01-05 03:40 UTC, skomma commented on README.md
> +# How to restore
他と揃えて、
```
How to restore
--------------
```
がいいかな。細かいけど。

2018-01-05 03:40 UTC, skomma commented on README.md
> +You can use restore command to restore database from backup file.
You can use **"restore"** command の方がいいかな。

2018-01-05 03:40 UTC, skomma commented on bin/restore.sh
> +# delete tarball if restore was successfully over
これコンテナが消えた時にファイルも消えるからいらんね。

2018-01-05 03:46 UTC, ryu-sato commented on README.md
> +# How to restore
Usageの1段落下として記載したつもりでしたが、意図した結果と違ったので直します。

2018-01-05 03:47 UTC, ryu-sato commented on README.md
> +You can use restore command to restore database from backup file.
修正します。

2018-01-05 03:49 UTC, ryu-sato commented on bin/restore.sh
> +# delete tarball if restore was successfully over
backup.sh の方では掃除していた（と思っていたが間違い）し、
コンテナを使いまわした時には一応掃除した方が良いかなと思って記載してました。
backup.sh の方では tar を削除するコードはコメントアウトされているようなので、
restore.sh も展開したファイルはコンテナ削除と共に消えるので対応不要としておきます。

2018-01-05 10:39 UTC, merged