Support/e2e test of gcs
weseek/mongodb-awesome-backup pull request #13
Opened 2019-03-10 06:29 UTC by ryu-sato

* GCS 用のテストを追加
    * それまで(S3用)のテストをディレクトリ S3 配下に配置
* テスト実行方法を CONTRIBUTING.md に記載
    * ついでに PR 作成方法を合わせて記載

以下、ついでに修正。

* `bin/boto.sh` が `GCP_ACCESS_KEY_ID` と `GCP_SECRET_ACCESS_KEY` を指定した場合であっても HMAC 認証をせずに OAuth で認証しようとする問題と、 OAuth 認証をしようとする際に `/mab` ディレクトリが存在せずに /mab/.boto が作成できずエラー終了してしまう問題を修正
* `test/s3/e2e.sh` 実行時に `app_restore`, `app_backup_cronmode` が強制 build されない問題を修正

2019-03-10 06:31 UTC, ryu-sato commented on test/s3/e2e.sh
> +docker-compose up --build app_restore
手元で動かした時に build されないことがありオプションが不足していることが分かったので、ついでに修正しました。(CircleCI では毎回 rebuild されるので CI には問題なかった)

2019-03-10 06:31 UTC, ryu-sato commented on test/s3/e2e.sh
> +docker-compose up --build app_backup_cronmode &
同上

2019-03-10 06:33 UTC, ryu-sato commented on bin/boto.sh
> +if [ -n "${GCP_ACCESS_KEY_ID}" ] && [ -n "${GCP_SECRET_ACCESS_KEY}" ]; then
ダブルクオートの位置がおかしいのと、条件の論理式が逆だったので修正。
正しくは `GCP_ACCESS_KEY_ID`, `GCP_SECRET_ACCESS_KEY` が指定された場合には、HMAC 認証用に `.boto` を作成しないといけない。

2019-03-10 06:34 UTC, ryu-sato commented on bin/boto.sh
> +  if [ ! -d ${MOUNT} ]; then mkdir -p ${MOUNT}; fi
/mab が存在しない(マウントされない) とエラー終了してしまうので、
マウントされない場合でも OAuth 認証が使えるように修正。

2019-03-12 00:38 UTC, skomma requested changes

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +* Please make sure to execute the test suite locally before posting your PR.
テストがパスすること、という書き方のほうがいいかも？

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +    * Executing **test for S3 is required**, and executing **test for GCS is not required**, but is expected.
expected ではなく preferred かな？

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +    * Notice that it **REMOVE ALL OBJECTS UNDER TARGET_BUCKET_URL**.
TARGET_BUCKET_URL をダブルクォートで囲った方が良さげ？

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +```
この pre、インデントしたほうがいい。
箇条書きの中に書くやつは全部それで。

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +* Set environment variables to execute mongo
mongo ではなく gsutil かな？

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +* Executing test script
なぜここだけ ing ついた？

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +* Executing test script
こっちもだった。ing

2019-03-12 00:38 UTC, skomma commented on CONTRIBUTING.md
> +* Executing test script
これも。

2019-03-12 00:38 UTC, skomma commented on test/gcs/docker-compose.yml
> +      TARGET_BUCKET_URL: $TARGET_BUCKET_URL
これ base_env にあるから不要？

2019-03-12 00:38 UTC, skomma commented on test/gcs/docker-compose.yml
> +      TARGET_BUCKET_URL: $TARGET_BUCKET_URL
これもbase_envにあるよね？

2019-03-12 00:38 UTC, skomma commented on test/gcs/docker-compose.yml
> +    entrypoint:
これ、`|` とかで指定したほうがキレイ？

2019-03-12 00:38 UTC, skomma commented on test/gcs/docker-compose.yml
> +        'while read line; do eval echo $$line; done < /tmp/.boto > /root/.boto
cp or シンボリックリンクでいいんじゃないの？

2019-03-12 00:38 UTC, skomma commented on test/gcs/e2e.sh
> +    echo "could not be found ${GCS_FILE_PATH} in GCS.";
受動態じゃなくてよくない？

2019-03-12 00:38 UTC, skomma commented on test/gcs/e2e.sh
> +start_mongo_service_and_init_service () {
引数の説明がほしい

2019-03-12 00:38 UTC, skomma commented on test/gcs/e2e.sh
> +  start_mongo_service_and_init_service ${WITH_BOTO[i]}
for の中身はそれぞれ function 化したいかなー

2019-03-12 00:45 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +        'while read line; do eval echo $$line; done < /tmp/.boto > /root/.boto
ここの処理によって /tmp/.boto に書かれた環境変数を展開してます。
コメント書いておきますね。

2019-03-12 17:23 UTC, ryu-sato commented on CONTRIBUTING.md
> +* Please make sure to execute the test suite locally before posting your PR.
確かに実行しても成功してないと意味がないですね。
修正します。

2019-03-12 17:30 UTC, ryu-sato commented on CONTRIBUTING.md
> +    * Executing **test for S3 is required**, and executing **test for GCS is not required**, but is expected.
日本語で言うと、開発者の役に立つ「推奨」というよりは、リポジトリメンテナとしての「希望」なのかなと思ったのですが、それでも preferred の方がよいですか？
わざわざ GCS バケットを用意してもらい、その上でテストを実行してもらうことを perferred というのは少し気が引けます。

2019-03-12 17:31 UTC, ryu-sato commented on CONTRIBUTING.md
> +    * Notice that it **REMOVE ALL OBJECTS UNDER TARGET_BUCKET_URL**.
修正します。

2019-03-12 17:31 UTC, ryu-sato commented on CONTRIBUTING.md
> +    * Executing **test for S3 is required**, and executing **test for GCS is not required**, but is expected.
一旦、上記都合を踏まえて改めて読み直してもらえますか？

2019-03-12 17:33 UTC, ryu-sato commented on CONTRIBUTING.md
> +```
Github でもインデントできるのですね。
修正します。
(Growi は使える、Qiita と Github は使えない、と理解してました)

2019-03-12 17:34 UTC, ryu-sato commented on CONTRIBUTING.md
> +* Set environment variables to execute mongo
gsutil が正しいです。修正します。

2019-03-12 17:38 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +    entrypoint:
修正します。

2019-03-12 17:47 UTC, ryu-sato commented on test/gcs/e2e.sh
> +    echo "could not be found ${GCS_FILE_PATH} in GCS.";
修正します。

2019-03-12 17:52 UTC, ryu-sato commented on test/gcs/e2e.sh
> +start_mongo_service_and_init_service () {
追記します。

2019-03-12 17:52 UTC, ryu-sato commented on test/gcs/e2e.sh
> +  start_mongo_service_and_init_service ${WITH_BOTO[i]}
修正します。

2019-03-12 17:55 UTC, ryu-sato commented on CONTRIBUTING.md
> +* Executing test script
実施する内容を箇条書きにしているから `Execute` の方がよいですかね。
修正します。

2019-03-12 17:55 UTC, ryu-sato commented on CONTRIBUTING.md
> +* Executing test script
`Execute` にします。

2019-03-12 17:56 UTC, ryu-sato commented on CONTRIBUTING.md
> +* Executing test script
`Execute` にします。

2019-03-12 17:57 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +      TARGET_BUCKET_URL: $TARGET_BUCKET_URL
確かに不要ですね。消します。

2019-03-12 17:57 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +      TARGET_BUCKET_URL: $TARGET_BUCKET_URL
確かに不要ですね。消します。

2019-03-16 07:14 UTC, skomma commented on CONTRIBUTING.md
> +    * Executing **test for S3 is required**, and executing **test for GCS is not required**, but is expected.
あーなるほど、expect は完全に「予期する」の意味だと思っていた。。。
というか文章全体読んでると、なんか意味が通らないような気もしてきた。
言いたいことはこういうことだよね？
```
S3 に対するテストが動くことは保証してほしくて、GCS に対するテストが動くことは可能であれば対応してほしい。
```

2019-03-16 07:22 UTC, skomma commented on test/gcs/docker-compose.yml
> +    entrypoint:
あんまりきれいじゃないなぁ…
もうちょっと何とかなる気が…

2019-03-16 07:25 UTC, skomma commented on test/gcs/docker-compose.yml
> +        'while read line; do eval echo $$line; done < /tmp/.boto > /root/.boto
なるほど、であれば envsubst コマンドが使えそう？

2019-03-16 07:27 UTC, skomma commented on test/gcs/e2e.sh
> +    echo "could not be found ${GCS_FILE_PATH} in GCS.";
うーむ、そこまで変えなくても、単純に `could not find` でいいと思った。

2019-03-16 07:31 UTC, skomma requested changes

2019-03-16 07:31 UTC, skomma commented on test/gcs/e2e.sh
> +#                       If set value true, initialize `/mab/.boto`.
`If set "true"` かなぁ。文字列であることがわからない。

2019-03-16 07:32 UTC, skomma commented on test/gcs/e2e.sh
> +  start_mongo_service_and_init_service ${WITH_BOTO[i]}
これだけあとでみる。

2019-03-16 08:33 UTC, ryu-sato commented on CONTRIBUTING.md
> +    * Executing **test for S3 is required**, and executing **test for GCS is not required**, but is expected.
テストを実行することが必須として書いた文章でした。

(PR を出す前にテストをローカルで実行して (OKだったら) PR を出して欲しい、という意図で書いてました。テストが通ることすら書いていないのは微妙)

テストが動くことは保証するニュアンスで書き直します。

2019-03-16 08:47 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +        'while read line; do eval echo $$line; done < /tmp/.boto > /root/.boto
envsubst 知りませんでした。まさしくやりたいことに合致するみたいなので修正します。

2019-03-16 08:57 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +    entrypoint:
パイプは改行維持だから全部の行に `\` を追加しないと shell 実行時に syntax error になります。(https://yaml.org/spec/1.2/spec.html)

>  Scalar content can be written in block notation, using a literal style (indicated by “|”) where all line breaks are significant. Alternatively, they can be written with the folded style (denoted by “>”) where each line break is folded to a space unless it ends an empty or a more-indented line. 

```
init_1                               | 2019/03/16 17:50:59 Waiting for: tcp://mongo:27017
init_1                               | 2019/03/16 17:50:59 Connected to tcp://mongo:27017
init_1                               | /bin/bash: -c: line 1: syntax error near unexpected token `&&'
init_1                               | /bin/bash: -c: line 1: `&& gsutil ls gs://staging.ryutest-99285.appspot.com/test/__/'
init_1                               | 2019/03/16 17:50:59 Command exited with error: exit status 1
mongo_1                              | 2019-03-16T17:50:59.388+0900 I -        [conn1] end connection 172.18.0.3:42854 (1 connection now open)
```

`|` は `>` に変えるとして、きれいの考え方は、entrypoint の各項目を1つのコマンドオプションとして分けられていることという観点になりますか？

2019-03-17 16:38 UTC, ryu-sato commented on test/gcs/e2e.sh
> +#                       If set value true, initialize `/mab/.boto`.
修正します。

2019-03-18 02:48 UTC, skomma commented on CONTRIBUTING.md
> +    * Please make sure to pass the **test for S3** at least, if possible make sure to pass the **test for GCS**.
とてもわかりやすくなった:+1:

2019-03-18 02:52 UTC, skomma requested changes

2019-03-18 02:52 UTC, skomma commented on test/gcs/docker-compose.yml
> +      # Evaluate each line in /tmp/.boto is used to expand variables.
動詞がダブってる

2019-03-18 02:52 UTC, skomma commented on test/gcs/docker-compose.yml
> +    entrypoint:
`|` の件の指示ミスはごめん。
「きれい」というのは、100% この書き方にしてほしいというわけではなくて、第三者(他人、未来の自分)が今後読んだときに分かりやすい、という観点での「きれい」で話していた。感覚的なもの。

っで、なんでオレが↑みたいな書き方を出したかというと、`/bin/bash` までは dockerize のオプションで、bash に渡すコマンドを明確に分けて書けたので出した、という経緯。

2019-03-18 14:23 UTC, ryu-sato commented on CONTRIBUTING.md
> +    * Please make sure to pass the **test for S3** at least, if possible make sure to pass the **test for GCS**.
ありがとう。 Resolve conversation にします。

2019-03-18 14:23 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +      # Evaluate each line in /tmp/.boto is used to expand variables.
気が付きませんでした。修正します。

2019-03-18 15:36 UTC, ryu-sato commented on test/gcs/docker-compose.yml
> +    entrypoint:
> * 第三者(他人、未来の自分)が今後読んだときに分かりやすい

entrypoint は YAML の配列で示すことが多いので一般的には見やすいのかもしれませんが、
行数が長くなるのは意味の塊が取れなくなって分かりづらいと思う意見もあるかなと思いました。
なので、「きれい」の意図を知りたかったです。

> * あとで修正しやすい

に対して、

> ダブルクォート・シングルクォートを混ぜて、環境変数展開まで使っているので、修正するときにいらんもので突っかかりそうだなぁという感触

これは確かにその通りだと思います。

出来れば(ダブル|シングル)クォートやエスケープは使わない方が、後に修正する時に変数の展開是非や閉じ忘れの防止につながると思います。

シェルスクリプトとして出してみましたけどどうでしょう。
これまでのやり取りで言う「きれい」な状態になったかと思います。

2019-03-19 02:52 UTC, skomma approved these changes

2019-03-19 02:52 UTC, skomma commented on test/gcs/docker-compose.yml
> +      - /root/entrypoint.init_test.sh
ここまでまとめられると、もはや Dockerfile.init_test に ENTRYPOINT を記載してもいいレベルだね。
まぁ、気が向いたらやるくらいで。

2019-03-19 02:53 UTC, merged