Add time to filename
weseek/mongodb-awesome-backup pull request #19
Opened 2019-06-26 02:21 UTC by skomma

2019-06-27 05:16 UTC, skomma commented on test/gcs/e2e.sh
> -REQUIRED_ENVS=("GCP_ACCESS_KEY_ID" "GCP_SECRET_ACCESS_KEY" "GCP_PROJECT_ID" "TARGET_BUCKET_URL" "DOT_BOTO_OAUTH")
`GCP_ACCESS_KEY_ID` と `GCP_SECRET_ACCESS_KEY` があれば、必ずしも必要には見えなかったので削った。

2019-06-27 05:16 UTC, skomma commented on test/gcs/entrypoint.init_test.sh
> +gsutil rm -rf ${TARGET_BUCKET_URL}**
gsutil の挙動がいつの間にか変わっていたようなので、修正。

```
  If you want to delete all objects in the bucket, but not the bucket itself,
  this command will work:

    gsutil rm gs://bucket/**
```

2019-06-27 05:16 UTC, skomma commented on test/s3/e2e.sh
> +  docker-compose exec s3proxy sh -c "ls /data/${S3_FILE_PATH} >/dev/null 2>&1"
`test -f` だと複数ファイルある場合に存在チェックができなくなっていたので、 `ls` を使う方法に修正。

2019-06-27 05:16 UTC, skomma commented on test/s3/e2e.sh
> +assert_file_exists_on_s3 "app_default/backup-${TODAY}*.tar.bz2"
実行時の時間によりファイル名が一意に確定できないため、ワイルドカードによる存在チェックにした。

2019-06-27 05:16 UTC, skomma commented on bin/backup.sh
> +NOW=`create_current_yyyymmddhhmmss`
本題。バックアップファイル名につける日付に時刻を足した。

2019-06-27 05:16 UTC, skomma commented on bin/functions.sh
>  create_today_yyyymmdd() {
テスト時に使うので、today は引き続き取っておいてある。

2019-06-27 05:16 UTC, skomma commented on test/gcs/e2e.sh
> +  assert_file_exists_on_gcs "backup-${TODAY}"
時刻が間に挟まるので、チェックする文字列を修正。

2019-06-27 05:16 UTC, skomma commented on test/gcs/Dockerfile.init_test
> +COPY dummy-backup-20180622000000.tar.bz2 /
バックアップ時のファイル名が変わるので、リストアテスト用のファイル名も併せて修正。

2019-06-28 03:31 UTC, ryu-sato requested changes

2019-06-28 03:31 UTC, ryu-sato commented on bin/functions.sh
>  create_today_yyyymmdd() {
使ってませんでした orz
機会があれば test で function.sh を取り込んで `create_today_yyyymmdd` を使うように修正ですかね。

https://github.com/weseek/mongodb-awesome-backup/blob/54b7cd544f1d8d647e7bc4c7c71864131ba4922f/test/s3/e2e.sh#L40
https://github.com/weseek/mongodb-awesome-backup/blob/54b7cd544f1d8d647e7bc4c7c71864131ba4922f/test/gcs/e2e.sh#L150

2019-06-28 03:31 UTC, ryu-sato commented on test/gcs/e2e.sh
> -REQUIRED_ENVS=("GCP_ACCESS_KEY_ID" "GCP_SECRET_ACCESS_KEY" "GCP_PROJECT_ID" "TARGET_BUCKET_URL" "DOT_BOTO_OAUTH")
GCS 用のテストでは GCP_ACCESS_KEY_ID と GCP_SECRET_ACCESS_KEY を使って mab を実行するケースと、
DOT_BOTO_OAUTH で指定された OAuth 設定ファイルを使って mab を実行するケースの 2 パターンをテストするので、 `DOT_BOTO_OAUTH` も必須項目です。(下記で使っている)

https://github.com/weseek/mongodb-awesome-backup/blob/54b7cd544f1d8d647e7bc4c7c71864131ba4922f/test/gcs/e2e.sh#L54

2019-06-28 03:52 UTC, skomma commented on test/gcs/e2e.sh
> -REQUIRED_ENVS=("GCP_ACCESS_KEY_ID" "GCP_SECRET_ACCESS_KEY" "GCP_PROJECT_ID" "TARGET_BUCKET_URL" "DOT_BOTO_OAUTH")
ここに書いてることと矛盾しない？

https://github.com/weseek/mongodb-awesome-backup/blob/54b7cd544f1d8d647e7bc4c7c71864131ba4922f/CONTRIBUTING.md#test-for-gcs-only

この手順の通りだと、 `DOT_BOTO_OAUTH` なんて環境変数は指定しないでテストを実行するように言ってるし、実際 `test/gcs/e2e.sh` は `conf/.boto_oauth` が存在していれば `DOT_BOTO_OAUTH` 環境変数はなくても動く。(= 必須じゃないと思ってる)

CircleCI で環境変数指定で渡すために使ってるとか？

2019-06-28 03:56 UTC, skomma commented on bin/functions.sh
>  create_today_yyyymmdd() {
ほんまや。

> 機会があれば test で function.sh を取り込んで create_today_yyyymmdd を使うように修正ですかね。

テストが本体側のコードを参照するのはなんかおかしい気もするので、いったん消した。

2019-06-28 04:03 UTC, ryu-sato approved these changes

2019-06-28 04:03 UTC, ryu-sato commented on test/gcs/e2e.sh
> -REQUIRED_ENVS=("GCP_ACCESS_KEY_ID" "GCP_SECRET_ACCESS_KEY" "GCP_PROJECT_ID" "TARGET_BUCKET_URL" "DOT_BOTO_OAUTH")
確かに手順と矛盾しますね。
必須ではなく、「`config/.boto_oauth` ファイルを作成するか、環境変数 `DOT_BOTO_OAUTH` を指定する必要がある」が正しいですね。
そうなると必須ではないので除外すべきだと思います。 👍

2019-06-28 04:04 UTC, merged