Feat/crond mode
weseek/mongodb-awesome-backup pull request #2
Opened 2018-05-18 10:07 UTC by ryu-sato

Review & merge task
* https://weseek.myjetbrains.com/youtrack/issue/INFRA-250

2018-05-19 05:30 UTC, skomma requested changes

2018-05-19 05:30 UTC, skomma commented on crontab/root
> +  0  4  *  *  * /opt/bin/backup.sh && /opt/bin/prune.sh && /opt/bin/list.sh
`CRONMODE=false` にして、entrypoint.sh を呼ぶようにしたいな。
というのは、今後もバックアップ元とバックアップ先の対応を広げていくのであれば、現状の entrypoint.sh で振り分けを行いたいから。
あと、このファイルってコンテナの中に入るの？使い方がよくわからないんだが。

2018-05-21 03:50 UTC, ryu-sato commented on crontab/root
> +  0  4  *  *  * /opt/bin/backup.sh && /opt/bin/prune.sh && /opt/bin/list.sh
Slack にて下記やり取りを行いました。

```
ryu [14:32]
ありがとう
cron ファイルは -v でボリュームマウントして使う想定です。(そうすれば時刻設定がイメージ作った後に簡単に出来る)
> CRONMODE=false にして、entrypoint.sh を呼ぶようにしたいな。
これは entrypoint.sh 内で CRONMODE=true/false を分岐させるわけではなく、CRONMODE=true/false で entrypoint.sh を呼ぶ・呼ばないを分けるということ？

syunsuke [14:45]
どちらでもよい
ただ、現状の entrypoint.shの内容をcronで (edited)
呼び出すようにしておいた方が
後々ラクかと思ってる
それはコメントに書いたことが理由
んーそれ、コマンド指定までそのcronにやらせるのか…
ryu
cron ファイルは -v でボリュームマウントして使う想定です。(そうすれば時刻設定がイメージ作った後に簡単に出来る)
Posted in #srvMay 19th
まーそれでいいならいいんだけど
コンテナを定期実行ってソリューションがないんだよなぁ
systemd timer で
restartPolicy を never にした docker-compose コンテナを記述しておいて
docker-compose up するやり方はダメなんかね
バックアップ用のコンテナは単体で docker-compose.yml に書いておけばそれで行けるような気がしないでもない
cron でやるというところからひっくり返してるけど…

ryu [15:03]
crondは使っても使わなくてもどちらでもいけると思ってます。
ただ、どちらを採用した方が良いか判断基準が無くて。
```

2018-05-21 06:05 UTC, skomma commented on crontab/root
> +  0  4  *  *  * /opt/bin/command_exec.sh backup prune list
まぁ、この方針でいいんだけど、 `/opt/bin/command_exec.sh` って設定する側が意識しないといけないってのはイケてないよねぇ～

2018-05-21 06:05 UTC, skomma approved these changes

2018-05-21 06:05 UTC, merged

2018-05-21 06:08 UTC, ryu-sato commented on crontab/root
> +  0  4  *  *  * /opt/bin/command_exec.sh backup prune list
そうですね。引数で時刻を指定した方が綺麗ですね。