add env var `CRON_EXPRESSION`
weseek/mongodb-awesome-backup pull request #4
Opened 2018-06-08 07:27 UTC by ryu-sato

Review & merge task
* https://weseek.myjetbrains.com/youtrack/issue/INFRA-269

2018-06-08 20:48 UTC, skomma commented on README.md
> +  -e CRON_EXPRESSION=<Cron expression (ex. express every four o'clock "0 4 * * *".)> \
`(ex. "0 4 * * *" if you want to run at 4:00 every day)` ですかね。

2018-06-08 20:48 UTC, skomma commented on README.md
> +Variables
Environment variables

2018-06-08 20:48 UTC, skomma commented on README.md
> +### variables for `backup`, `prune`, `list`
For `backup`, `prune`, `list`

2018-06-08 20:48 UTC, skomma commented on README.md
> +| CRONMODE          | If you set true, executed in cron mode. In cron mode, backup is executed at time which is specified by `CRON_EXPRESSION`. | false   |
ここの true って文字列よね？
であれば、 `"true"` とクォートしておいたほうがよさげ。
あと、 `docker run` 時の引数が渡るよ、という話がないので…

If set `"true"`, this container is executed in cron mode. In cron mode, the script will be executed with the specified arguments and at the time specified by `CRON_EXPRESSION`.

とか？長い気もするが。

2018-06-08 20:48 UTC, skomma commented on README.md
> +| CRON_EXPRESSION   | Cron expression. (ex. every four o'clock is expressed by "0 4 * * *".)                                                    | -       |
ここも↑と同じ感じで。

2018-06-08 20:48 UTC, skomma commented on README.md
> +### variables for `restore`
For `restore`

2018-06-08 20:48 UTC, skomma commented on README.md
> +| MONGORESTORE_DROPOPT | Throw '--drop' option to mongorestore | -       |
Throw -> Add かなぁ。

2018-06-09 04:42 UTC, ryu-sato commented on README.md
> +| CRONMODE          | If you set true, executed in cron mode. In cron mode, backup is executed at time which is specified by `CRON_EXPRESSION`. | false   |
なるほど。追加します。

2018-06-09 04:44 UTC, ryu-sato commented on README.md
> +| MONGORESTORE_DROPOPT | Throw '--drop' option to mongorestore | -       |
修正します。

2018-06-09 04:45 UTC, ryu-sato commented on README.md
> +  -e CRON_EXPRESSION=<Cron expression (ex. express every four o'clock "0 4 * * *".)> \
修正します。

2018-06-18 01:41 UTC, skomma requested changes

2018-06-18 01:41 UTC, skomma commented on README.md
> +| MONGORESTORE_DROPOPT | Add '--drop' option to mongorestore | -       |
単語しか指摘しなかったけど、これ具体的に何指定すればいいかわからんな…
っで、別に DROPOPT の true/false じゃなくて `MONGORESTORE_OPTS` とか汎用的なもののほうがいいのでは？

2018-06-18 01:56 UTC, ryu-sato commented on README.md
> +| MONGORESTORE_DROPOPT | Add '--drop' option to mongorestore | -       |
簡単に修正できるようなら実装を共に変更しつつ README.md を編集し、
簡単に修正できないようなら一旦 `MONGORESTORE_DROPOPT` に値として何を追加すればよいのかを記載することにします。

2018-06-18 08:56 UTC, merged