support/e2e-test
weseek/mongodb-awesome-backup pull request #6
Opened 2018-06-11 01:34 UTC by ryu-sato

Reivew & merge task
* https://weseek.myjetbrains.com/youtrack/issue/INFRA-274

docker-compose を使った e2e テストを追加

2018-06-11 02:03 UTC, skomma requested changes

2018-06-11 02:03 UTC, skomma commented on Dockerfile.test
> +LABEL maintainer="WESEEK <info@weseek.co.jp>"
maintainer は自信を持って自分の名前で！
あと、description がほしい。

2018-06-11 02:03 UTC, skomma commented on Dockerfile.test
> +RUN pip install awscli
e2e にするなら、この辺は base の Dockerfile から作った Docker image のものを使いたいなぁ。

2018-06-11 02:03 UTC, skomma commented on test/Dockerfile.util
> +LABEL maintainer="WESEEK <info@weseek.co.jp>"
ここも。

2018-06-11 02:03 UTC, skomma commented on test/docker-compose.yml
> +    depends_on:
depends_on とか links はもはや不要なはず。
どうせ、dockerize で待つし。

http://docs.docker.jp/compose/startup-order.html

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +COMPOSE_PROJECT_NAME=mongodbawesomebackuptest
これは .env に移動したいところ。
https://docs.docker.com/compose/env-file/

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +# sleep while backup is executed in cron mode (at leat 60s)
least

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +# sleep while backup is executed in cron mode (at leat 60s)
なぜ 60 秒待つのかコメントが欲しい。

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +echo "***** ALL TEST ARE SUCCESS *****"
ALL TESTS ARE SUCCESSFUL だな

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +## should exit code is 0
exit code should be 0

2018-06-11 02:03 UTC, skomma commented on test/e2e.sh
> +  docker-compose -p ${COMPOSE_PROJECT_NAME} -f test/docker-compose.yml up -d --build
-d せずに `&` でバックグラウンドで動かしたらログが出てくるしいいんじゃないかしら？

2018-06-11 02:10 UTC, ryu-sato commented on test/e2e.sh
> +  docker-compose -p ${COMPOSE_PROJECT_NAME} -f test/docker-compose.yml up -d --build
なるほど。試して適宜修正しますね。

2018-06-11 02:10 UTC, ryu-sato commented on test/e2e.sh
> +## should exit code is 0
修正します。

2018-06-11 02:10 UTC, ryu-sato commented on test/e2e.sh
> +echo "***** ALL TEST ARE SUCCESS *****"
修正します。

2018-06-11 02:10 UTC, ryu-sato commented on test/e2e.sh
> +# sleep while backup is executed in cron mode (at leat 60s)
追記します。

2018-06-11 02:12 UTC, ryu-sato commented on test/e2e.sh
> +COMPOSE_PROJECT_NAME=mongodbawesomebackuptest
test 配下の .env に追加してうまく行かなかったのでそうしました。(テスト内で変数としても使っているので)
.env に移動できるかもう一度検討してみます。

2018-06-11 02:14 UTC, ryu-sato commented on test/docker-compose.yml
> +    depends_on:
dockerize で待つので depends_on が要らないことは納得しましたが、links は mongodb に接続するために必要と思ったので要否確認してから適宜修正します。

2018-06-11 02:15 UTC, ryu-sato commented on Dockerfile.test
> +LABEL maintainer="WESEEK <info@weseek.co.jp>"
本体の Dockerfile コピペしただけなのですが。 :-P
適宜修正しておきます。

2018-06-11 02:17 UTC, ryu-sato commented on Dockerfile.test
> +RUN pip install awscli
そう。そうなんですが aws コマンドを s3proxy に向けられず、苦慮した結果こうしました。
本体　base の Dockerfile を修正して、本番かテストかで分岐させるとかですかね。

2018-06-18 02:43 UTC, ryu-sato commented on test/docker-compose.yml
> +    depends_on:
docker-compose yml version 2 から links を設定しなくても service 名でアクセスできるようになったのですね。
今回は version 3 なので不要と理解しました。

2018-06-18 04:06 UTC, ryu-sato commented on .gitignore
> +./.env
test 配下の .env ファイルが repository 管理できていなかったため修正。

2018-06-18 04:06 UTC, ryu-sato commented on Dockerfile
> +# install dockerize(it is needed by e2e test)
e2e test で対象とする Dockerfile を本番で利用するものと同じにするため dockerize をインストールすることにしました。

2018-06-18 04:07 UTC, ryu-sato commented on bin/functions.sh
> +AWSCLIOPT=${AWSCLIOPT:-}
e2e test 時に awscli コマンドの接続先を変更したいため AWSCLIOPT を追加しました。
※ 初期値は空なので記載する必要はありませんが、変数を内部で利用していることが分かりやすいように記載しています。

2018-06-18 08:59 UTC, skomma commented on .gitignore
> +./.env
頭のコロンいらなくない？

2018-06-18 09:25 UTC, skomma requested changes

2018-06-18 09:25 UTC, skomma commented on test/Dockerfile.util
> +FROM alpine:3.7
この Dockerfile いる？
ルートの Dockerfile で事足りるよね？

2018-06-18 09:25 UTC, skomma commented on test/docker-compose.yml
> +         && curl --request PUT http://s3proxy:80/app_restore'"
このコンテナ、まとめないで各コンテナで起動時にやればいいんじゃない？

2018-06-18 09:25 UTC, skomma commented on test/e2e.sh
> +# check a S3 file is exist
動詞が2つある

2018-06-18 09:25 UTC, skomma commented on test/e2e.sh
> +# app_default
コメントがここだけ違う…

2018-06-18 09:25 UTC, skomma commented on test/e2e.sh
> +check_s3_file_exist ${S3_ENDPOINT_URL} "app_restore/backup-${TODAY}.tar.bz2"
restore の確認になってない？

2018-06-18 09:38 UTC, ryu-sato commented on .gitignore
> +./.env
なるほど。確認して適宜修正します。

2018-06-18 09:39 UTC, ryu-sato commented on test/docker-compose.yml
> +         && curl --request PUT http://s3proxy:80/app_restore'"
言われてみれば確かにそうですね。
そうなると Dockerfile.util もいらないですね。

2018-06-18 09:43 UTC, ryu-sato commented on test/e2e.sh
> +# check a S3 file is exist
修正します。

2018-06-18 09:43 UTC, ryu-sato commented on test/e2e.sh
> +# app_default
気が付きませんでした。修正します。

2018-06-18 09:44 UTC, ryu-sato commented on test/e2e.sh
> +check_s3_file_exist ${S3_ENDPOINT_URL} "app_restore/backup-${TODAY}.tar.bz2"
確かに restore 出来たかどうかは確認できていないです。よい方法が浮かばなかったもので。
ちょっと考えます。

2018-06-19 02:45 UTC, ryu-sato commented on test/Dockerfile.util
> +FROM alpine:3.7
Dockerfile.util (仮名) の役割が変わりそうなのでこのコメントは一旦置いておきます。

2018-06-25 01:44 UTC, skomma requested changes

2018-06-25 01:44 UTC, skomma commented on test/e2e.sh
> +docker-compose down
-v 追加で。
mongodb とかデフォルトで volume を残すけど、docker-compose.yml に明記しなくても消えるのか要チェック。

2018-06-25 01:44 UTC, skomma commented on test/e2e.sh
> +docker-compose down
-v 追加で。

2018-06-25 01:44 UTC, skomma commented on test/e2e.sh
> +# Wait while container exist
コメント要修正

2018-06-25 01:44 UTC, skomma commented on test/docker-compose.yml
> +  init_s3proxy_and_mongo:
init でいいんじゃない？

2018-06-25 01:44 UTC, skomma commented on test/e2e.sh
> +check_s3_file_exist() {
check... はよくない。
https://qiita.com/KeithYokoma/items/2193cf79ba76563e3db6

テストだったら、`assert_file_exists_on_s3` とか？

2018-06-25 01:53 UTC, skomma requested changes

2018-06-25 01:53 UTC, skomma commented on test/.env
> +COMPOSE_PROJECT_NAME=mongodbawesomebackuptest
これ、docker-compose が読み込む `.env` として必要なのは、↑の行だけだよね？
コンテナ内でだけ必要な、↓3行は別ファイルに分離してほしいかなぁ。

2018-06-25 01:53 UTC, skomma commented on test/e2e.sh
> +  curl -I -L --silent "${ENDPOINT_URL}/${S3_FILE_PATH}" 2>&1 | grep -e '^HTTP/' | grep -q '200 OK'
末尾の grep は `'^HTTP/.\+200 OK'` にまとめられるね。

2018-06-25 01:53 UTC, skomma commented on test/e2e.sh
> +stop_docker_container "app_backup_cronmode" "-t 65"
docker-compose stop じゃダメなのかい？

```
$ docker-compose stop --help
Stop running containers without removing them.

They can be started again with `docker-compose start`.

Usage: stop [options] [SERVICE...]

Options:
  -t, --timeout TIMEOUT      Specify a shutdown timeout in seconds.
                             (default: 10)
```

2018-06-25 01:53 UTC, skomma commented on test/e2e.sh
> +if [ "x${DUMMY_RECORD_NUM}" = "x1" ]; then echo 'FAILED'; exit 1; fi
↑2行は関数化したほうがよいのでは？

2018-06-25 01:53 UTC, skomma commented on test/e2e.sh
> +wait_docker_container "init_s3proxy_and_mongo"
`wait_docker_container` のところってコンテナが終了するまで待つんだよね？

`-d` なしの `docker-compose up init` で終了したら戻ってこないかしら？

2018-06-25 02:18 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose down
確認して修正します。

2018-06-25 02:18 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose down
確認して修正します。

2018-06-25 02:18 UTC, ryu-sato commented on test/e2e.sh
> +# Wait while container exist
適宜修正します。

2018-06-25 02:20 UTC, ryu-sato commented on test/docker-compose.yml
> +  init_s3proxy_and_mongo:
出来る限り説明した方がよいと思いましたが、伝わるようなら短い方がよいので修正します。

2018-06-25 02:24 UTC, ryu-sato commented on test/e2e.sh
> +check_s3_file_exist() {
確かに何を check するのか分からないですね。(期待する動作が分からない)
修正します。

> そういえば、この関数は return してるだけだけど、テスト失敗した場合は途中で終了とかしないでいいの？

function の return が 0 以外であれば bash -e で終了するのでその点は大丈夫です。

2018-06-25 02:26 UTC, ryu-sato commented on test/.env
> +COMPOSE_PROJECT_NAME=mongodbawesomebackuptest
いや、docker-compose が読み込む .env で4行すべて必要です。
e2e.sh では COMPOSE_PROJECT_NAME だけ流用してますが、そっちのことを言ってますか？

2018-06-25 02:26 UTC, ryu-sato commented on test/e2e.sh
> +  curl -I -L --silent "${ENDPOINT_URL}/${S3_FILE_PATH}" 2>&1 | grep -e '^HTTP/' | grep -q '200 OK'
そうですね。まとめます。

2018-06-25 02:29 UTC, ryu-sato commented on test/e2e.sh
> +stop_docker_container "app_backup_cronmode" "-t 65"
ああ、行けそうですね。修正します。

2018-06-25 02:29 UTC, ryu-sato commented on test/e2e.sh
> +if [ "x${DUMMY_RECORD_NUM}" = "x1" ]; then echo 'FAILED'; exit 1; fi
assert～ といった関数名で作成しておきます。

2018-06-25 02:32 UTC, ryu-sato commented on test/e2e.sh
> +wait_docker_container "init_s3proxy_and_mongo"
戻ってくる気がしますね。確認して適宜修正します。

2018-06-25 08:58 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose down
volume は残ってました。 `-v` オプションをつけることにします。

2018-06-25 10:08 UTC, ryu-sato commented on test/e2e.sh
> +wait_docker_container "init_s3proxy_and_mongo"
戻ってきませんでした。

2018-06-25 10:19 UTC, ryu-sato commented on test/e2e.sh
> +wait_docker_container "init_s3proxy_and_mongo"
考えてみれば init が終了しても s3proxy や mongo は起動したままなのでフォアグラウンドで実行することはできませんでしたね。

2018-06-26 01:43 UTC, skomma requested changes

2018-06-26 01:43 UTC, skomma commented on test/docker-compose.yml
> +      - AWS_ACCESS_KEY_ID=testid
yaml の参照を使った List のマージってできないんだっけ？
マージできないから全部書き直してる系？

2018-06-26 01:43 UTC, skomma commented on test/e2e.sh
> +trap 'rc=$?; trap - EXIT; handle_exit; exit $?' INT PIPE TERM
参考にしたページがあるならコメントで書いておいて。

2018-06-26 01:43 UTC, skomma commented on test/e2e.sh
> +# assert restore successful
restore **is** successful

2018-06-26 01:43 UTC, skomma commented on test/e2e.sh
> +wait_docker_container "init"
`docker-compose run init` でも init 単体で待てなかった？

2018-06-26 02:06 UTC, ryu-sato commented on test/e2e.sh
> +wait_docker_container "init"
やってみます。

2018-06-26 02:06 UTC, ryu-sato commented on test/e2e.sh
> +# assert restore successful
修正します。

2018-06-26 02:06 UTC, ryu-sato commented on test/e2e.sh
> +trap 'rc=$?; trap - EXIT; handle_exit; exit $?' INT PIPE TERM
追加します。

2018-06-26 02:07 UTC, ryu-sato commented on test/docker-compose.yml
> +      - AWS_ACCESS_KEY_ID=testid
app_default のマージでは反映されませんでした。
environment に名前を付けてマージできるかどうかは試していないので試してみます。

2018-06-26 02:39 UTC, ryu-sato commented on test/docker-compose.yml
> +      - AWS_ACCESS_KEY_ID=testid
environment にアンカー付けてマージできたので修正します。

2018-06-27 04:10 UTC, ryu-sato commented on test/e2e.sh
> +wait_docker_container "init"
run でも up でも事前に s3proxy, mongo を立ち上げた後に init 単体で指定して FG で実行すれば、実行完了を待つことはできましたが、下記エラーとなりました。
sleep 3 を挟むと成功するため、恐らく network が初期化される前に docker-compose up を連続実行しているのが問題だと思われます。

```
  : <snip>
mongodbawesomebackuptest_init_1 exited with code 0
ERROR: 2 matches found based on name: network mongodbawesomebackuptest_default is ambiguous
  : <snip>
```

2018-06-28 06:38 UTC, skomma requested changes

2018-06-28 06:38 UTC, skomma commented on test/e2e.sh
> +sleep 3 # wait for that network of docker-compose is ready
`wait for the network of docker-compose to be ready`

2018-06-28 06:38 UTC, skomma commented on test/e2e.sh
> +docker-compose up --build app_restore
ここ以降の `docker-compose up` には `--build` はいらないんじゃないか？
app_default と同じイメージを使うのよね？

2018-06-28 06:38 UTC, skomma commented on test/e2e.sh
> +sleep 3 # wait for that network of docker-compose is ready
こっちのコメントも要修正

2018-06-28 06:38 UTC, skomma commented on test/e2e.sh
> +docker-compose stop -t 65 app_backup_cronmode
ん～ここの `-t` は↑の sleep と一緒にしちゃっていいんじゃない？

2018-06-28 06:41 UTC, ryu-sato commented on test/e2e.sh
> +sleep 3 # wait for that network of docker-compose is ready
修正します。

2018-06-28 06:41 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose up --build app_restore
同じイメージを使うので要らないですね。消しておきます。

2018-06-28 06:41 UTC, ryu-sato commented on test/e2e.sh
> +sleep 3 # wait for that network of docker-compose is ready
修正します。

2018-06-28 06:42 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose stop -t 65 app_backup_cronmode
> ん～ここの -t は↑の sleep と一緒にしちゃっていいんじゃない？
これ、ダメだったんです。。。
docker-compose up -> stop を sleep 入れずに実行するとエラー (network がほげほげ)
なので、ここにも sleep は入れる必要ありそうです。

2018-06-28 07:06 UTC, ryu-sato commented on test/e2e.sh
> +docker-compose stop -t 65 app_backup_cronmode
-t 65 は削除して、sleep の方にまとめて sleep 65 にする方針で行きます。
待機する理由はコメントに記載します。

2018-06-28 08:57 UTC, merged