Support/circleci
weseek/mongodb-awesome-backup pull request #7
Opened 2018-07-01 10:28 UTC by ryu-sato

この PR は、e2e テストを CircleCI v2 で実施するための ./circleci/config.yml を追加し、合わせて CircleCI 環境でも e2e.sh を実行できるよう(もちろん Linux で docker ホストからも実行できるまま) 修正してます。

2018-07-01 10:29 UTC, ryu-sato commented on test/docker-compose.yml
> -    expose:
docker-compose 内で expose は不要だったため削除しました。

2018-07-01 10:30 UTC, ryu-sato commented on test/docker-compose.yml
> -    ports:
e2e.sh からアクセスするために用意した ports は不要になったため削除しました。

2018-07-01 10:30 UTC, ryu-sato commented on test/e2e.sh
> -#!/bin/bash -e
`-e` オプションをつけていたところ function 内でコマンドを実行して戻り値が 0 以外になった場合も終了してしまっていたため、オプションを削除しました。

2018-07-01 10:31 UTC, ryu-sato commented on test/e2e.sh
> -S3_ENDPOINT_URL="http://localhost:10080"
assert_file_exists_on_s3 で利用してましたが、docker-compose exec を利用するよう修正して不要になったため削除しました。

2018-07-01 10:32 UTC, ryu-sato commented on test/e2e.sh
> +  docker-compose exec s3proxy sh -c "test -f /data/${S3_FILE_PATH}"
CircleCI では DOCKER_HOST が e2e.sh を実行するホストとは別にあり、localhost ではアクセスできなかったため docker-compose exec に変更しました。

2018-07-01 10:33 UTC, ryu-sato commented on test/e2e.sh
> +# Clear trap
正常終了時も EXIT をフックして docker-compose down -v を実行してしまい、docker network の remove 処理が2度行われてエラーとなったため、Trap を解除する処理を追加しました。

2018-07-02 01:27 UTC, skomma requested changes

2018-07-02 01:27 UTC, skomma commented on .circleci/config.yml
> +      - image: ubuntu:xenial
bionic が最新だけど bionic じゃなくていいの？

2018-07-02 01:27 UTC, skomma commented on .circleci/config.yml
> +      DOCKER_COMPOSE_VER: 1.11.2
こちらも最新じゃない感。
https://docs.docker.com/release-notes/docker-ce/
https://github.com/docker/compose/releases

2018-07-02 14:20 UTC, ryu-sato commented on README.md
> +[![CircleCI](https://circleci.com/gh/weseek/mongodb-awesome-backup/tree/master.svg?style=shield)](https://circleci.com/gh/weseek/mongodb-awesome-backup/tree/master)
CircleCI のビルドステータスを示すバッジを追加しました。

2018-07-04 04:50 UTC, skomma approved these changes

2018-07-04 04:50 UTC, merged